version: "3.0"
services:
  
  rdbm:
    image: mariadb:10.3.16
    environment:
      MYSQL_ROOT_PASSWORD: "devops"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.0.4
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - rdbm

volumes:
  db: